### ISSUE TITLE
Manual return instead of setting ctx.status and ctx.body only

### ISSUE THREAD

**Issue by Jonarod** [markusahlstrand/cloudworker-router#11]
Nice repo, thanks!

However I might have missed something down the road: what can we do besides set `ctx.status` and `ctx.body` ??

I naively tried:

```
router.post('/hello', async (ctx) => {
  try {
    const body = await ctx.event.request.json()
    ctx.body = JSON.stringify(body)+'\n';
    ctx.status = 200;      
  } catch (error) {
    ctx.status = 401;
  }
});
```
status code is never set because of the `await` function. 

Is there a way to decide when to `return`?

Something like:
```
router.post('/hello', async (ctx) => {
  try {
    const body = await ctx.event.request.json()

    return res.status(200).json(body)
  } catch (error) {
    return res.status(401)
  }
});
```

**Comment by markusahlstrand** [comment]
Hi @Jonarod!

Turns out the is a bug.. Thanks for reporting it :) The code you posted above should almost work, you just need to write the status and the body back to the context like this:

```
router.post('/hello', async (ctx) => {
  try {
    const body = await ctx.request.json();
    ctx.body = JSON.stringify(body);
    ctx.status = 200;
  } catch (error) {
    console.log(error.message);
    ctx.status = 400;
  }
});
```

Thanks again for reporting!

**Comment by Jonarod** [comment]
Your solution yields an error:

```
SyntaxError: Unexpected token o in JSON at position 1
```

This is why I went with `await ctx.event.request.json()` because I found that `await ctx.request.json()` yields nothing... But this is, IMO, another issue.

What I meant is that any kind of `await` will not be respected, like:

```
const fetchSomething = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res('hello')
    }, 100);
  })
}


router.post('/hello', async (ctx) => {
  try {
    const resp = await fetchSomething()
    ctx.body = resp;
    ctx.status = 200;      
  } catch (error) {
    ctx.status = 401;
  }
});
```
will return a `404` instead of either `200` or `401` because the `await` is not awaited and thus `ctx.status` never modified.

**Comment by markusahlstrand** [comment]
I think this should work with the latest version.. Are you using 1.9.1?

The example folder in the project is deployed to http://router.cloudproxy.io and I added a new sample there to validate the async functionality: http://router.cloudproxy.io/wait

You can also try posting a json object to http://router.cloudproxy.io/hello which will echo the body back.

Does this solve the issue for you?

**Comment by Jonarod** [comment]
Ok I got it. I was implementing a middleware like:

```
router.use(async (ctx, next) => {
  const apikey = ctx.event.request.headers.get('Authorization')
  if(!apikey){
    ctx.status = 401;
  } else {
    next(ctx);
  }
});
```

I was not considering `next()` as an `async` function... Now it works after adding `await` to the `next()` function, like this:

```
router.use(async (ctx, next) => {
  const apikey = ctx.event.request.headers.get('Authorization')
  if(!apikey){
    ctx.status = 401;
  } else {
    await next(ctx);  // <<< ADDED await HERE
  }
});
```

Thanks for your support :)
