### ISSUE TITLE
Error previewing from "wrangler preview"

### ISSUE THREAD

**Issue by LeCodeCo** [markusahlstrand/cloudworker-router#14]
First of all, thanks for creating this. I've been looking in using Cloudflare Workers more and this will really help make it easier.

When I install the module from NPM and make an index.js then run `wrangler preview`, I see this. https://i.imgur.com/32OKd0I.png

```
const router = require('cloudworker-router');

router.get('/', async (ctx) => {
    ctx.body = 'Hello World';
    ctx.status = 200;
});

addEventListener('fetch', event => {
    event.respondWith(router.resolve(event));
})
```

Is there any other code I need which I can find an example from? I'm terribly sorry if this is a dumb question.

Thanks!

**Comment by markusahlstrand** [comment]
I use the router together with serverless and serverless-offline for local debugging (there's a sample in the example folder), so there might be some issues using it with wrangler that I'm not aware of. Does wrangler support using require in the files?

I'll take a closer look today as it would be nice to compatible with wrangler.

**Comment by markusahlstrand** [comment]
Turned out that the documentation is a bit off. The router is a class that needs to be instantiated which I missed in the docs.  I'll push an update for the docs and a wrangler folder inside the examples with a version that works.

```
const Router = require("cloudworker-router");

const router = new Router();

router.get("/", async (ctx) => {
  ctx.body = "Hello World";
  ctx.status = 200;
});

addEventListener("fetch", (event) => {
  event.respondWith(router.resolve(event));
});
```

If you haven't, also checkout the cloudworker-proxy that is based on the router and has a bunch of pre-built handlers for common tasks such as logging, authentication and load-balancing.

**Comment by markusahlstrand** [comment]
Think the debug experience with wrangler is pretty limited. So far I'm pretty happy with using the shims from node-cloudworkers which allows you to run on top of node locally. This way you can set break points and write tests like any other server side code.. Might be good with wrangler as a complement to make sure it runs fine in the actual cloudworker environment.

**Comment by LeCodeCo** [comment]
Works perfectly now with the added router class. Thanks a bunch, and I'll be sure to take a look at the cloudworker-proxy repo again in more detail.

**Comment by markusahlstrand** [comment]
Perfect, let me know if you have any other questions or if there's some other functionality you would like to add to the router.
