### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by rande** [markusahlstrand/cloudworker-router#20]
Hello,

Do you plan to add TypeScript support for this module ?

Thanks.

**Comment by markusahlstrand** [comment]
Hi @rande!

We have been discussing making a new version of the cloudworker-proxy that uses this module under the hood, so it would make sense to convert this module to typescript as well. Think it hopefully shouldn't be too much work, but haven't written any modules in typescript yet, so not sure if there's any gotchas.. Would you be interested in helping out?

**Comment by rande** [comment]
I don't want to commit to help you on that task, I have very random free time.  The first step can be to include the module definition (before converting the code to TS). I made a quick one yesterday night (London time zone).

```ts
declare module 'cloudworker-router' {
  export type Request = {
    body: ReadableStream
    headers: { [index: string]: string }
    host: string
    hostname: string
    href: string
    json: (maxSize: number) => Promise<any>
    method: string
    origin: string
    protocol: string
    query: { [index: string]: string }
    querystring: string
    search: string
    text: (maxSize: number) => Promise<string>
  }

  export type Handler = (ctx: Context) => Promise<void>
  export type Middleware = (ctx: Context, next: Handler) => Promise<void>

  export class Context {
    request: Request
    event: string
    state: object
    cloned: boolean
    response: {
      headers: { [index: string]: string } // HeadersInit ?
    }
    body: string
    status: number
    query: object

    header(key: string): string
    set(key: string, value: string): void
    clone(): Context
  }

  export class Router {
    get(path: string, handler: Handler): void
    post(path: string, handler: Handler): void
    get(path: string, handler: Handler): void
    del(path: string, handler: Handler): void
    use(middleware: Middleware): void

    resolve(event: FetchEvent): Promise<Response>
  }
}

```

I thing the `add` method from the router is missing.

**Comment by markusahlstrand** [comment]
Cool, haven't done that before but looks simple enough. I'll see if I can add this to a branch and we can see if we can get it right.

**Comment by markusahlstrand** [comment]
A bit late, but finally made a rewrite in typescript :)
