### ISSUE TITLE
Middleware auth

### ISSUE THREAD

**Issue by adammeyer** [markusahlstrand/cloudworker-router#38]
I'm not sure how to implement middleware.  If an auth middleware passes, how do I continue onto the next handler?

**Comment by markusahlstrand** [comment]
Hi @adammeyer!

It's just to return next(ctx) and it will pass the request to the next handler

You can check out the middlewares in the proxy repo for insperation: https://github.com/markusahlstrand/cloudworker-proxy/blob/master/src/handlers/basic-auth.js

Let me know if it's still unclear
