### ISSUE TITLE
Redirects?

### ISSUE THREAD

**Issue by coughlanio** [markusahlstrand/cloudworker-router#42]
Hi,

Is there a way to handle redirects/301/302?

Thanks,
Chris

**Comment by markusahlstrand** [comment]
You can do it manually by setting the location header of the response, but we should really support it the same way koa does it with `ctx.redirect()`. I'll see if I can add that to the next release

**Comment by coughlanio** [comment]
Perfect!

```javascript
ctx.response.headers["location"] = url;
ctx.response.headers["Content-Type"] = "audio/mp4";
ctx.status = 301;
```

Thanks!
