### ISSUE TITLE
How to render a external html file?

### ISSUE THREAD

**Issue by pakkographic** [markusahlstrand/cloudworker-router#46]
Hello,

I want to know how to send file to response/render an external html file like Express.js `response.sendFile(__dirname + './home.html'); `

Can you help me?

**Comment by markusahlstrand** [comment]
That's a good question :) There's not really a filesystem that you can access on the cloudflare workers, so you would have to solve it slightly differently. What I typically do is to store the file in KV-Storage which is pretty close to how it would work in express. We have a middleware for doing that in proxy that you could get insperation from: https://github.com/markusahlstrand/cloudworker-proxy/blob/master/src/handlers/kv-storage-binding.js

I wanted to migrate these middlewares to a separate project so you can use it easily in the router but haven't yet found the time to do it.. 

Another way would be to store it as string in a js file that you could import, but it's not very elegant.

Let me know if this helped you or now.

Best,
Markus

**Comment by pakkographic** [comment]
Hello again,

I need some precisions with the kvStorageBinding()
I want to know what value I need to put in  :

kvNamespaceBinding 
kvBasePath
kvKey
defaultExtension
defaultIndexDocument
defaultErrorDocument

I already know some values to put but i just want to be sure.

Thanks for your help.

**Comment by pakkographic** [comment]
Hello again,

I need some precisions with the kvStorageBinding()
I want to know what value I need to put in :

kvNamespaceBinding
kvBasePath
kvKey
defaultExtension
defaultIndexDocument
defaultErrorDocument

I already know some values to put but i just want to be sure.

Thanks for your help.

**Comment by pakkographic** [comment]
Can you reply, please?

**Comment by pakkographic** [comment]
I'm waiting your help.

**Comment by markusahlstrand** [comment]
Hi @pakkographic,

The very simplest solution would be something like this:

```
router.get('/test', async (ctx) => {
    const value = await NAMESPACE.get('someKey');    
    ctx.status = value ? 200 : 404;
    ctx.body = value;
});
```

There is more documentation on KV-storage here: https://developers.cloudflare.com/workers/runtime-apis/kv

**Comment by pakkographic** [comment]
Thanks for your help.
