### ISSUE TITLE
Pass bindings to routes context

### ISSUE THREAD

**Issue by haleksandre** [markusahlstrand/cloudworker-router#65]
With the new module worker syntax (https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#syntax-module-worker) `bindings` are no longer global. Instead they are passed as a second argument to exporte`fetch` function. With that being said, it would be useful to be able to pass those `bindings` to the routes' context, either within `state` object or within it's own special property `env` / `bindings`.

A work around is you can pass a modified `request` with the `bindings` to the `Router.handle`, but this causes a typing issue & then to use the `bindings` you need to dig into `ctx.event.request`. It would be preferable to be able to add the `bindings` directly to routes' context.

**Comment by markusahlstrand** [comment]
Hi, sorry for the slow reply. Just bumped into the same issue and will be doing a patch for this now.

**Comment by markusahlstrand** [comment]
Pushed version 3.0 which takes a request, env and execution context. It's also a generic class now so you can pass the Env strictly typed.
