### ISSUE TITLE
No Request or Query data in the context object

### ISSUE THREAD

**Issue by vsxed** [markusahlstrand/cloudworker-router#76]
Hello!

Just checked out this module and wanted to try it.

After setting it up, it seems like there is no data inside `ctx.request` and `ctx.query` etc. event though a form body was posted.
Same happens with simple GET requests.
Is this a known issue or just an user error?

This is my setup:

`index.ts`
```typescript
import { Router } from 'cloudworker-router'

const router = new Router();

router.post('/hello/:name', async (ctx) => {
    return new Response(JSON.stringify(ctx));
  });

export default {
    async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
        return router.handle(request, env, ctx);
    },
};
```

And this is the result:

![image](https://user-images.githubusercontent.com/1070998/203181204-43082c79-78db-4666-9fa5-65065e077c51.png)

**Comment by markusahlstrand** [comment]
Hi @vsxed ,

Sorry for the late reply.

The body isn't part of the request by default as it isn't loaded yet.

You can get the body in a json format like this:
`const body = await ctx.request.json()
`
In the new v4-version which is currently in beta there's also a bodyparser middleware included which automatically will parse the body. Think I'll merge this to master some time next week.
